---

- name: Start Containers on Machines
  hosts: all # this can be overwritten with the --limit option when starting the playbook
  tasks:
    - name: Start Containers
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        auto_remove: yes
        log_driver: journald
        env_file: "{{ container_dirname }}/env_file.env"
        volumes:
          - "{{ container_dirname }}:{{ container_dirname }}"